version: '3'

services:
  php-fpm:
    build: docker/php-fpm
    container_name: doingsdone-php-fpm
    working_dir: /application
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - .:/application

  nginx:
    image: nginx:latest
    container_name: doingsdone-nginx
    working_dir: /application
    ports:
      - "8081:80"
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
